theme: jekyll-theme-modernist

# Chabanel
## Chabanel
### Chabanel
![Ateneo](https://jhs.adnu.edu.ph/pluginfile.php/1/theme_remui/section_html/942325426/welcomebg.png)

<iframe width="560" height="315" src="https://www.youtube.com/embed/KSX4cwWRzis?si=j0u4ElQtVEFje92v" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/0bYg9bo50gSsH3LtXe2SQn?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
